// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // from docs/intro.md
    },
    {
      type: 'doc',
      id: 'rating', // from docs/rating.md
    },
    {
      type: 'doc',
      id: 'contact-us', // from docs/contact-us.md
    },
    {
      type: 'doc',
      id: 'support', // from docs/support.md
    },
    {
      type: 'category',
      label: 'App Documentation',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'app_setup',
        },
      ],
    },
  ],
};

export default sidebars;
