// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index', // ✅ corrected here
    },
    {
      type: 'doc',
      id: 'rating',
    },
    {
      type: 'doc',
      id: 'contact-us',
    },
    {
      type: 'doc',
      id: 'support',
    },
    {
      type: 'category',
      label: 'App Documentation',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'app_setup',
        },
      ],
    },
  ],
};

export default sidebars;
